name: CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  call-sphinx-workflow:
    permissions:
      contents: write # To push a branch
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    uses: ./.github/workflows/sphinx.yml
  call-release-workflow:
    permissions:
      id-token: write
    uses: ./.github/workflows/release.yml